spring.application.name=MyBlog
spring.data.mongodb.uri=${MONGODB_URI}
spring.mvc.hiddenmethod.filter.enabled=true
logging.level.com.example.MyBlog=DEBUG
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html