spring.application.name=MyBlog
spring.data.mongodb.uri=mongodb+srv://testadm:Afmin@learningmongo.wznd2xq.mongodb.net/Myblog?retryWrites=true&w=majority&appName=learningMongo
spring.mvc.hiddenmethod.filter.enabled=true
logging.level.com.example.MyBlog=DEBUG
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html